<?php

namespace App\Jobs;

use App\Exceptions\Ai\AiBudgetExceededException;
use App\Exceptions\Ai\AiException;
use App\Models\Application;
use App\Models\CoverLetter;
use App\Models\CoverLetterVersion;
use App\Models\JobPosting;
use App\Models\Profile;
use App\Models\User;
use App\Services\Ai\AiClientFactory;
use App\Services\Ai\Prompt;
use App\Services\CompanyContextService;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Support\Facades\Log;

/**
 * Generates cover-letter variants for one application (T-52). Fans out across the
 * requested angle variants — story_led / results_led / culture_led — creating one
 * CoverLetterVersion per successful Claude call, all grounded in real company
 * facts from CompanyContextService (PLAN §5/§7: no hallucinated company claims).
 *
 * PHP has no true parallelism in a single worker, so the variants are generated
 * sequentially; each call is isolated so one variant's failure — or a mid-fan-out
 * budget stop — never discards the variants already produced.
 *
 * Runs in an unauthenticated worker, so all lookups bypass the BelongsToUser scope
 * and user_id is set explicitly on every row written.
 */
class GenerateLetterJob implements ShouldQueue
{
    use Queueable;

    /** The variant angles generated by default, mapped to letter_<variant>.v1 prompts. */
    public const DEFAULT_VARIANTS = ['story_led', 'results_led', 'culture_led'];

    public int $tries = 1;

    /**
     * @param  array{length_hint?: string, tone?: string, custom_instructions?: string|null, variants?: list<string>}  $params
     */
    public function __construct(
        public readonly int $coverLetterId,
        public readonly array $params = [],
    ) {
        $this->onQueue('ai');
    }

    public function handle(AiClientFactory $factory, CompanyContextService $companyContext): void
    {
        $coverLetter = CoverLetter::withoutGlobalScopes()->find($this->coverLetterId);
        if ($coverLetter === null) {
            return;
        }

        $application = Application::withoutGlobalScopes()->find($coverLetter->application_id);
        if ($application === null) {
            return;
        }

        $user = User::find($coverLetter->user_id);
        if ($user === null) {
            return;
        }

        $jobPosting = $application->job_posting_id !== null
            ? JobPosting::find($application->job_posting_id)
            : null;
        $profile = Profile::withoutGlobalScopes()->where('user_id', $user->id)->first();

        $lengthHint = (string) ($this->params['length_hint'] ?? 'medium');
        $tone = (string) ($this->params['tone'] ?? 'professional');
        $customInstructions = trim((string) ($this->params['custom_instructions'] ?? '')) ?: 'none';

        $variants = $this->params['variants'] ?? self::DEFAULT_VARIANTS;

        // Distill company facts once and reuse across every variant (T-50).
        $facts = $companyContext->factsFor(
            $jobPosting?->company ?? '',
            $jobPosting?->apply_url,
        );
        $companyContextUsed = $facts !== null && trim($facts) !== '';
        $companyContextText = $companyContextUsed ? $facts : 'not provided';

        $client = $factory->forUser($user);

        foreach ($variants as $variant) {
            $promptVersion = "letter_{$variant}.v1";

            if (! Prompt::exists($promptVersion)) {
                Log::warning('Skipping unknown letter variant', [
                    'cover_letter_id' => $coverLetter->id,
                    'variant' => $variant,
                ]);

                continue;
            }

            $content = Prompt::render($promptVersion, [
                'job_title' => $jobPosting?->title ?? 'the role',
                'company' => $jobPosting?->company ?? 'the company',
                'job_description' => $jobPosting?->jd_text ?? 'not provided',
                'resume_text' => $profile?->resume_text ?: 'not provided',
                'voice_profile' => $this->voiceProfileText($profile),
                'company_context' => $companyContextText,
                'length_hint' => $lengthHint,
                'tone' => $tone,
                'custom_instructions' => $customInstructions,
            ]);

            try {
                $response = $client->messages(
                    [
                        'max_tokens' => 1500,
                        'messages' => [['role' => 'user', 'content' => $content]],
                    ],
                    purpose: 'letter',
                    referenceType: CoverLetter::class,
                    referenceId: $coverLetter->id,
                    promptVersion: $promptVersion,
                );
            } catch (AiBudgetExceededException $e) {
                // Hard cap hit mid-fan-out: stop, but keep the variants already made.
                Log::warning('Letter generation stopped by spend cap', [
                    'cover_letter_id' => $coverLetter->id,
                    'variant' => $variant,
                    'reason' => $e->getMessage(),
                ]);

                break;
            } catch (AiException $e) {
                // One variant failed; the ledger recorded it — keep generating the rest.
                Log::warning('Letter variant generation failed', [
                    'cover_letter_id' => $coverLetter->id,
                    'variant' => $variant,
                    'reason' => $e->getMessage(),
                ]);

                continue;
            }

            $draft = trim($response->text);
            if ($draft === '') {
                continue;
            }

            $version = CoverLetterVersion::create([
                'user_id' => $user->id,
                'cover_letter_id' => $coverLetter->id,
                'content_md' => $draft,
                'variant_label' => $variant,
                'generation_params' => [
                    'prompt_version' => $promptVersion,
                    'variant' => $variant,
                    'length_hint' => $lengthHint,
                    'tone' => $tone,
                    'custom_instructions' => $customInstructions,
                    'company_context_used' => $companyContextUsed,
                    'model' => $response->model,
                ],
            ]);

            // Give the UI a default the first time a variant lands.
            if ($coverLetter->active_version_id === null) {
                $coverLetter->active_version_id = $version->id;
                $coverLetter->save();
            }
        }
    }

    /**
     * Encode the user's voice profile as a compact string for the prompt, or the
     * sentinel "not provided" when they haven't captured one yet.
     */
    private function voiceProfileText(?Profile $profile): string
    {
        $voice = $profile?->voice_profile;

        if (empty($voice)) {
            return 'not provided';
        }

        return json_encode($voice, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?: 'not provided';
    }
}
